---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: Copy artifact.tar.gz into remotes
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/download/artifact.tar.gz

- name: Extract artifact.tar.gz into /backend
  unarchive:
    src: ~/download/artifact.tar.gz
    dest: ~/backend

- name: start application
  become: true
  tasks:
    - name: Run application
      shell: |
        cd backend
        npm install
        pm2 stop default
        pm2 start npm -- start
