---
- name: Creates backend
  file:
    path: ~/backend
    state: directory

- name: Extract artifact.tar.gz into /backend
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name: start application
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
